### ISSUE TITLE
main-sim.R expects assertthat library

### ISSUE THREAD

**Issue by goose0058** [PredictiveEcology/LandWeb#120]
There is at least one call to assert_that() invoked in main-sim.R, but that library doesn't seem to be loaded by default and throws an error. For now I am just manually doing `library(assertthat)` and main-sim.R executes successfully.

As of today (October 29, 2020) I am running the latest version of LandWeb; the last commit was c93c54da86b046e76fef5262e9fdfdb9a8db5cb9.

**Comment by achubaty** [comment]
Ah, thanks for catching that. We had removed `assertthat` as a dependency for some SpaDES/LandR packages, so that's likely why it wasn't being loaded (but why you still already had it installed).

I've made a couple changes to README and scripts to ensure it's installed.
