### ISSUE TITLE
Invalid study area name does not raise an error

### ISSUE THREAD

**Issue by goose0058** [PredictiveEcology/LandWeb#121]
Hi Folks,

Just noticed that entering a study area name that does not match with any of the intended study areas does not raise an error. Instead, a random study area is selected. This means that a typo or other mistake can persist through one or several runs of the model, with the user only realizing their mistake when viewing the results. This is particularly possible when preamble results are cached and process quickly. Line 181 in `LandWeb_preamble.R` gives the user a warning message indicating a random study area will be used, but for some reason it doesn't seem to be executed. Can't figure out why.

Can we write in a check a the beginning of the model run that raises an exception if the user enters an invalid study area?

Thanks!

**Comment by achubaty** [comment]
That's a good idea. Should be easy to implement.

**Comment by achubaty** [comment]
Done. You may need to adjust your LandWeb_preamble to account for any custom areas you have added.
