### ISSUE TITLE
Error installing packages

### ISSUE THREAD

**Issue by chrismallon** [PredictiveEcology/LandWeb#124]
Hello, 

Thank you as always for the hard work everyone is putting into the LandWeb project. While updating to the latest commit, `03-packages.R` raised the following error:

```
The downloaded source packages are in
	‘/tmp/RtmpVCt8Ok/downloaded_packages’
 -- Installing PredictiveEcology/map@development -- (28 of 30. Estimated time left: 9 secs; est. finish: 2021-06-23 14:43:57)
Using github PAT from envvar GITHUB_PAT
 -- Installing PredictiveEcology/LandR@development -- (29 of 30. Estimated time left: 6 secs; est. finish: 2021-06-23 14:43:56)
Using github PAT from envvar GITHUB_PAT
 -- Installing ianmseddy/LandR.CS@master (>= 0.0.2.0002) -- (30 of 30. Estimated time left: 3 secs; est. finish: 2021-06-23 14:43:54)
Using github PAT from envvar GITHUB_PAT
Error: .onLoad failed in loadNamespace() for 'Rcpp', details:
  call: new_dummyObject(.dummyInstancePointer)
  error: object 'class__dummyInstance' not found
```
My first attempt to debug the problem was to attempt an install using `devtools`. Upon doing so, a very strange error was raised:

```
> devtools::install_github('PredictiveEcology/map@development')
Error: .onLoad failed in loadNamespace() for 'ellipsis', details:
  call: eval_bare(expr, env)
  error: object 'ellipsis_eval_bare' not found
```
This error happened after updating the code to the latest version, so the library did have other packages inside it. The `03-packages.R` script has streamlined the installation process, but there are regular errors that persist, like the ones above.

Here is the `sessionInfo`:

```
> sessionInfo()
R version 4.1.0 (2021-05-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.1 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_CA.UTF-8        LC_COLLATE=en_CA.UTF-8    
 [5] LC_MONETARY=en_CA.UTF-8    LC_MESSAGES=en_CA.UTF-8   
 [7] LC_PAPER=en_CA.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] data.table_1.13.0 Require_0.0.8    

loaded via a namespace (and not attached):
 [1] lattice_0.20-44     R6_2.4.1            rlang_0.4.11       
 [4] R.utils_2.10.1      R.oo_1.24.0         compiler_4.1.0     
 [7] codetools_0.2-18    R.methodsS3_1.8.1   grid_4.1.0         
[10] DBI_1.1.0           cli_2.5.0           remotes_2.2.0      
[13] RApiSerialize_0.1.0 RColorBrewer_1.1-2  tools_4.1.0        
[16] glue_1.4.2          yaml_2.2.1          parallel_4.1.0  
```

Thank you for your time and attention!

**Comment by achubaty** [comment]
The latest development version has fixed many of these 'quirks', but I have noticed in other contexts that this `Rcpp` error occurs and can be fixed by reinstalling `Rcpp`.

**Comment by achubaty** [comment]
You should restart your R session after reinstalling `Rcpp`, and try the package installation again.

**Comment by eliotmcintire** [comment]
Hi @chrismallon, this is a standard error that is due to attempts to detach some packages that were already loaded when your installation started. This should disappear with a session restart. There was a message that was at the top of that output stating something like "you may have to restart your session".

**Comment by chrismallon** [comment]
Thanks @achubaty and @eliotmcintire! Appreciate the prompt support. All packages are now updated the updated model runs. However, I was unable to do this by only using the scripts included with LandWeb. 

Here is the workflow I used to get everything working. This is not intended critically; only as an example of an outsider working with your code, on an unfamiliar machine.

1) After the initial error reported here, as per your feedback, I cleared the package directory to start from a fresh installation of all packages, and restarted from scratch.

2) I updated QGIS to the latest version (including GEOS 3.9.0).

3) I then began running the scripts in `00_global.R` one at a time, allowing the new package directory to be installed, and packages to be installed as needed.

4) Upon running `03_packages.R`, I begun running into dependency problems. The first problem was that `rgdal_1.5-16` had been installed. I restarted and installed the latest version (with the commented-out code in `03_packages.R`). 

5) Subsequent errors generally took the form of packages failing to build when a package that was already loaded needed to be updated. A common culprit was Rcpp:
`namespace ‘Rcpp’ is imported by ‘raster’ so cannot be unloaded`
This was solved by building all github-hosted packages first, using `devtools::install_github()`. 

6) Once all github-hosted packages were built, I then went back and ran the scripts in `00_global.R` order. I got a few more errors:
a. `packages ‘MarkEdmondson1234/googleID’, ‘jimhester/archive’ are not available for this version of R`
b. A similar error for `ianmseddy/LandR.CS@master`
These were also solved by building them in order, one at a time, with `devtools::install_github()`. Some further restarts were required.

7) Then the model ran!

Again, your work is sincerely appreciated. This kind of challenge is very normal in my experience of deploying models into new environments. 

I seemed to have more success when building the github-hosted packages first. Here are two suggestions for your consideration:

1) Re-order the installation workflow in `03_packages.R` to build all remotely hosted packages first, and
2) Consider using a tool other than `Require` for versioning.  Perhaps `renv`?

Thank you again for all the work you do!

**Comment by achubaty** [comment]
Thanks Chris, I had gone through all of this making the switch to R 4.1, but I'll revisit to ensure it's working.

Recall that the [README](https://github.com/PredictiveEcology/LandWeb/blob/master/README.md#prerequisites) identifies several prerequisites that need to be installed first. However, I can work these into the script workflow so that those aren't required in the README.

**Comment by eliotmcintire** [comment]
@achubaty did you work in the new `SpaDES.install` content into this LandWeb script?

**Comment by achubaty** [comment]
No, not yet
